// ============================================================================
// VibeL JS-ESM Code Generator — Phase 3
// Spec Reference: §21.6, §21.7
//
// Translates the VibeL AST into JavaScript ES Modules with embedded
// runtime verification. Each .vbl file becomes a .js module.
// ============================================================================

import {
  Program, Definition, FunctionDef, TypeDef, DataDef, EnumDef, UnionDef,
  AliasDef, ExternalDef, ValidatorDef, Statement, Expression, TypeExpr,
  LetStmt, AssignStmt, WriteStmt, CallStmt, ReturnStmt, AbortStmt,
  RollbackStmt, IfStmt, MatchStmt, ForStmt, WhileStmt, NotifyStmt,
  EmitStmt, AssertStmt, RecordField,
} from '../ast/nodes.js';

// ============================================================================
// Code Generation Options
// ============================================================================

export interface CodegenOptions {
  /** Include runtime verification checks (default: true) */
  verification?: boolean;
  /** Minify output (default: false) */
  minify?: boolean;
  /** Include source maps placeholder comments (default: true) */
  sourceMaps?: boolean;
  /** Trust proofs — skip runtime checks for PROVED BY functions */
  trustProofs?: boolean;
}

// ============================================================================
// Code Generator — Main Entry
// ============================================================================

export function generateJS(ast: Program, options: CodegenOptions = {}): string {
  const gen = new JSCodeGenerator(ast, {
    verification: options.verification ?? true,
    minify: options.minify ?? false,
    sourceMaps: options.sourceMaps ?? true,
    trustProofs: options.trustProofs ?? false,
  });
  return gen.generate();
}

// ============================================================================
// Internal Generator
// ============================================================================

class JSCodeGenerator {
  private ast: Program;
  private opts: Required<CodegenOptions>;
  private indent: number = 0;
  private output: string[] = [];
  private needsRuntime = false;

  constructor(ast: Program, opts: Required<CodegenOptions>) {
    this.ast = ast;
    this.opts = opts;
  }

  generate(): string {
    this.output = [];

    // File header
    this.emit('// ============================================================================');
    this.emit(`// Generated by VibeL Compiler v0.1.0 — target: js-esm`);
    this.emit(`// Source module: ${this.ast.module.path.join('.')}`);
    this.emit(`// Generated at: ${new Date().toISOString()}`);
    this.emit('// ============================================================================');
    this.emit('');

    // Imports
    this.emitImports();

    // Type definitions (as JSDoc + factory functions)
    for (const def of this.ast.definitions) {
      this.emitDefinition(def);
      this.emit('');
    }

    // Runtime helper injection (if needed)
    if (this.needsRuntime) {
      this.emitRuntimeHelpers();
    }

    return this.output.join('\n');
  }

  // ==========================================================================
  // Imports
  // ==========================================================================

  private emitImports(): void {
    // VibeL runtime import (always needed for verification)
    if (this.opts.verification) {
      this.emit("import { __vibelVerify, __vibelPrior, __vibelJournal, __vibelRollback, __vibelAbort } from '@vibelang/runtime';");
      this.emit('');
    }

    // User imports
    for (const imp of this.ast.imports) {
      const path = imp.path.join('/');
      this.emit(`import * as ${imp.alias} from './${path}.js';`);
    }

    if (this.ast.imports.length > 0) this.emit('');
  }

  // ==========================================================================
  // Definitions
  // ==========================================================================

  private emitDefinition(def: Definition): void {
    switch (def.kind) {
      case 'FunctionDef': this.emitFunction(def); break;
      case 'TypeDef': this.emitType(def); break;
      case 'DataDef': this.emitData(def); break;
      case 'EnumDef': this.emitEnum(def); break;
      case 'UnionDef': this.emitUnion(def); break;
      case 'AliasDef': this.emitAlias(def); break;
      case 'ValidatorDef': this.emitValidator(def); break;
      case 'ExternalDef': this.emitExternal(def); break;
    }
  }

  // ==========================================================================
  // Function Definition — the core code generation
  // ==========================================================================

  private emitFunction(fn: FunctionDef): void {
    const exportKw = fn.exported ? 'export ' : '';
    const params = fn.parameters.map(p => p.name).join(', ');

    // JSDoc
    this.emit('/**');
    this.emit(` * @intent ${fn.intent}`);
    for (const p of fn.parameters) {
      this.emit(` * @param {${this.typeToJSDoc(p.paramType)}} ${p.name}`);
    }
    this.emit(` * @returns {${this.typeToJSDoc(fn.returnType)}}`);
    this.emit(' */');

    this.emit(`${exportKw}async function ${fn.name}(${params ? `{ ${params} }` : ''}, __ctx = {}) {`);
    this.indent++;

    // --- Runtime verification wrapper ---
    if (this.opts.verification && (fn.ensureBefore.length > 0 || fn.ensureAfter.length > 0 || fn.invariants.length > 0)) {
      this.emitVerificationWrapper(fn);
    } else {
      this.emitFunctionBody(fn);
    }

    this.indent--;
    this.emit('}');
  }

  // ==========================================================================
  // Verification Wrapper (§21.7)
  // ==========================================================================

  private emitVerificationWrapper(fn: FunctionDef): void {
    // PRIOR() capture
    if (fn.effects.reads.length > 0 || fn.effects.writes.length > 0) {
      this.emit('// PRIOR() capture');
      this.emit('const __prior = {};');
      const allFields = [...fn.effects.reads, ...fn.effects.writes];
      for (const field of allFields) {
        const key = field.join('.');
        this.emit(`__prior['${key}'] = structuredClone(__ctx.readField?.('${key}'));`);
      }
      this.emit('');
    }

    // Write journal
    this.emit('const __journal = [];');
    this.emit('let __failureReason = null;');
    this.emit('');

    // ENSURE BEFORE
    if (fn.ensureBefore.length > 0) {
      this.emit('// ENSURE BEFORE');
      for (const spec of fn.ensureBefore) {
        const label = spec.label || 'precondition';
        const condition = this.emitSpecExpr(spec.expression);
        this.emit(`if (!(${condition})) {`);
        this.indent++;
        this.emit(`__failureReason = 'PreconditionFailed: [${label}]';`);
        // Dispatch ON FAILURE
        this.emitOnFailureBlock(fn);
        this.indent--;
        this.emit('}');
      }
      this.emit('');
    }

    // INVARIANT pre-check
    if (fn.invariants.length > 0) {
      this.emit('// INVARIANT (pre)');
      for (let i = 0; i < fn.invariants.length; i++) {
        const condition = this.emitSpecExpr(fn.invariants[i]);
        this.emit(`if (!(${condition})) {`);
        this.indent++;
        this.emit(`__failureReason = 'InvariantViolated: invariant_${i} (pre)';`);
        this.emitOnFailureBlock(fn);
        this.indent--;
        this.emit('}');
      }
      this.emit('');
    }

    // BODY in try/catch
    this.emit('// BODY');
    this.emit('let __returnValue;');
    this.emit('try {');
    this.indent++;
    this.emitFunctionBody(fn, true);
    this.indent--;
    this.emit('} catch (__err) {');
    this.indent++;
    this.emit('if (__err instanceof __VibeAbort) {');
    this.indent++;
    this.emit('__failureReason = __err.reason;');
    this.emitOnFailureBlock(fn);
    this.indent--;
    this.emit('} else { throw __err; }');
    this.indent--;
    this.emit('}');
    this.emit('');

    // Re-read fields for postcondition checking
    if (fn.effects.reads.length > 0 || fn.effects.writes.length > 0) {
      this.emit('// Re-read fields for postcondition checking');
      this.emit('const __current = {};');
      const allFields = [...fn.effects.reads, ...fn.effects.writes];
      for (const field of allFields) {
        const key = field.join('.');
        this.emit(`__current['${key}'] = __ctx.readField?.('${key}');`);
      }
      this.emit('');
    }

    // ENSURE AFTER
    if (fn.ensureAfter.length > 0) {
      this.emit('// ENSURE AFTER');
      for (let i = 0; i < fn.ensureAfter.length; i++) {
        const condition = this.emitSpecExpr(fn.ensureAfter[i], true);
        this.emit(`if (!(${condition})) {`);
        this.indent++;
        this.emit(`__failureReason = 'PostconditionFailed: postcondition_${i}';`);
        this.emitRollbackAndFailure(fn);
        this.indent--;
        this.emit('}');
      }
      this.emit('');
    }

    // INVARIANT post-check
    if (fn.invariants.length > 0) {
      this.emit('// INVARIANT (post)');
      for (let i = 0; i < fn.invariants.length; i++) {
        const condition = this.emitSpecExpr(fn.invariants[i], true);
        this.emit(`if (!(${condition})) {`);
        this.indent++;
        this.emit(`__failureReason = 'InvariantViolated: invariant_${i} (post)';`);
        this.emitRollbackAndFailure(fn);
        this.indent--;
        this.emit('}');
      }
      this.emit('');
    }

    // ON SUCCESS
    if (fn.onSuccess.length > 0) {
      this.emit('// ON SUCCESS');
      for (const stmt of fn.onSuccess) {
        this.emitStatement(stmt);
      }
      this.emit('');
    }

    this.emit('return __returnValue;');
    this.needsRuntime = true;
  }

  private emitOnFailureBlock(fn: FunctionDef): void {
    for (const stmt of fn.onFailure) {
      this.emitStatement(stmt);
    }
    this.emit('return;');
  }

  private emitRollbackAndFailure(fn: FunctionDef): void {
    this.emit('// Rollback writes');
    this.emit('for (let __i = __journal.length - 1; __i >= 0; __i--) {');
    this.indent++;
    this.emit('__ctx.writeField?.(__journal[__i].field, __journal[__i].priorValue);');
    this.indent--;
    this.emit('}');
    this.emitOnFailureBlock(fn);
  }

  // ==========================================================================
  // Function Body
  // ==========================================================================

  private emitFunctionBody(fn: FunctionDef, useReturnValue = false): void {
    for (const stmt of fn.body) {
      if (useReturnValue && stmt.kind === 'ReturnStmt') {
        // Capture return value instead of returning directly
        this.emit(`__returnValue = ${this.emitExpr(stmt.value)};`);
      } else {
        this.emitStatement(stmt);
      }
    }
  }

  // ==========================================================================
  // Statements
  // ==========================================================================

  private emitStatement(stmt: Statement): void {
    switch (stmt.kind) {
      case 'LetStmt': this.emitLet(stmt); break;
      case 'AssignStmt': this.emitAssign(stmt); break;
      case 'WriteStmt': this.emitWrite(stmt); break;
      case 'CallStmt': this.emitCall(stmt); break;
      case 'ReturnStmt': this.emitReturn(stmt); break;
      case 'AbortStmt': this.emitAbort(stmt); break;
      case 'RollbackStmt': this.emitRollback(stmt); break;
      case 'IfStmt': this.emitIf(stmt); break;
      case 'MatchStmt': this.emitMatch(stmt); break;
      case 'ForStmt': this.emitFor(stmt); break;
      case 'WhileStmt': this.emitWhile(stmt); break;
      case 'NotifyStmt': this.emitNotify(stmt); break;
      case 'EmitStmt': this.emitEmitStmt(stmt); break;
      case 'AssertStmt': this.emitAssert(stmt); break;
    }
  }

  private emitLet(stmt: LetStmt): void {
    const kw = stmt.mutable ? 'let' : 'const';
    this.emit(`${kw} ${stmt.name} = ${this.emitExpr(stmt.value)};`);
  }

  private emitAssign(stmt: AssignStmt): void {
    this.emit(`${stmt.target} = ${this.emitExpr(stmt.value)};`);
  }

  private emitWrite(stmt: WriteStmt): void {
    const key = stmt.target.join('.');
    const value = this.emitExpr(stmt.value);

    // Journal the write
    this.emit(`__journal.push({ field: '${key}', priorValue: structuredClone(__ctx.readField?.('${key}')), newValue: ${value} });`);

    if (stmt.mode === 'APPEND') {
      this.emit(`{ const __arr = __ctx.readField?.('${key}') ?? []; __arr.push(${value}); __ctx.writeField?.('${key}', __arr); }`);
    } else {
      this.emit(`__ctx.writeField?.('${key}', ${value});`);
    }
  }

  private emitCall(stmt: CallStmt): void {
    const target = stmt.target.join('.');
    const args = stmt.args.length > 0
      ? `{ ${stmt.args.map(a => `${a.name}: ${this.emitExpr(a.value)}`).join(', ')} }`
      : '';

    if (stmt.resultBinding) {
      this.emit(`const ${stmt.resultBinding} = await ${target}(${args});`);
    } else {
      this.emit(`await ${target}(${args});`);
    }
  }

  private emitReturn(stmt: ReturnStmt): void {
    this.emit(`return ${this.emitExpr(stmt.value)};`);
  }

  private emitAbort(stmt: AbortStmt): void {
    this.emit(`throw new __VibeAbort(${this.emitExpr(stmt.reason)});`);
    this.needsRuntime = true;
  }

  private emitRollback(stmt: RollbackStmt): void {
    this.emit('// ROLLBACK ALL WRITES');
    this.emit('for (let __i = __journal.length - 1; __i >= 0; __i--) {');
    this.indent++;
    this.emit('__ctx.writeField?.(__journal[__i].field, __journal[__i].priorValue);');
    this.indent--;
    this.emit('}');
    if (stmt.andAbort && stmt.reason) {
      this.emit(`throw new __VibeAbort(${this.emitExpr(stmt.reason)});`);
      this.needsRuntime = true;
    }
  }

  private emitIf(stmt: IfStmt): void {
    this.emit(`if (${this.emitExpr(stmt.condition)}) {`);
    this.indent++;
    for (const s of stmt.thenBlock) this.emitStatement(s);
    this.indent--;

    for (const clause of stmt.elseIfClauses) {
      this.emit(`} else if (${this.emitExpr(clause.condition)}) {`);
      this.indent++;
      for (const s of clause.body) this.emitStatement(s);
      this.indent--;
    }

    if (stmt.elseBlock.length > 0) {
      this.emit('} else {');
      this.indent++;
      for (const s of stmt.elseBlock) this.emitStatement(s);
      this.indent--;
    }

    this.emit('}');
  }

  private emitMatch(stmt: MatchStmt): void {
    const subject = this.emitExpr(stmt.subject);
    const tempVar = `__match_${Date.now() % 10000}`;
    this.emit(`const ${tempVar} = ${subject};`);

    for (let i = 0; i < stmt.cases.length; i++) {
      const c = stmt.cases[i];
      const prefix = i === 0 ? 'if' : '} else if';
      this.emit(`${prefix} (${tempVar}?.__type === '${c.pattern}' || ${tempVar}?.constructor?.name === '${c.pattern}') {`);
      this.indent++;
      if (c.binding) {
        this.emit(`const ${c.binding} = ${tempVar};`);
      }
      for (const s of c.body) this.emitStatement(s);
      this.indent--;
    }

    if (stmt.wildcard) {
      this.emit('} else {');
      this.indent++;
      for (const s of stmt.wildcard) this.emitStatement(s);
      this.indent--;
    }

    this.emit('}');
  }

  private emitFor(stmt: ForStmt): void {
    const coll = this.emitExpr(stmt.collection);
    if (stmt.indexVariable) {
      this.emit(`for (let ${stmt.indexVariable} = 0; ${stmt.indexVariable} < (${coll}).length; ${stmt.indexVariable}++) {`);
      this.indent++;
      this.emit(`const ${stmt.variable} = (${coll})[${stmt.indexVariable}];`);
    } else {
      this.emit(`for (const ${stmt.variable} of (${coll})) {`);
      this.indent++;
    }
    for (const s of stmt.body) this.emitStatement(s);
    this.indent--;
    this.emit('}');
  }

  private emitWhile(stmt: WhileStmt): void {
    this.emit(`while (${this.emitExpr(stmt.condition)}) {`);
    this.indent++;
    for (const s of stmt.body) this.emitStatement(s);
    this.indent--;
    this.emit('}');
  }

  private emitNotify(stmt: NotifyStmt): void {
    const target = stmt.target.join('.');
    this.emit(`await ${target}(${this.emitExpr(stmt.message)});`);
  }

  private emitEmitStmt(stmt: EmitStmt): void {
    const event = stmt.event.join('.');
    this.emit(`__ctx.emit?.('${event}', ${this.emitExpr(stmt.data)});`);
  }

  private emitAssert(stmt: AssertStmt): void {
    this.emit(`if (!(${this.emitExpr(stmt.condition)})) { throw new Error(${this.emitExpr(stmt.reason)}); }`);
  }

  // ==========================================================================
  // Expressions → JavaScript
  // ==========================================================================

  private emitExpr(expr: Expression): string {
    switch (expr.kind) {
      case 'LiteralExpr':
        if (expr.literalType === 'Text') return JSON.stringify(expr.value);
        if (expr.literalType === 'Nothing') return 'null';
        if (expr.literalType === 'Boolean') return expr.value ? 'true' : 'false';
        return String(expr.value);

      case 'IdentifierExpr':
        // Handle built-in functions
        if (expr.name === 'NOW') return 'Date.now()';
        if (expr.name === 'UUID') return 'crypto.randomUUID()';
        if (expr.name === 'FAILURE_REASON') return '__failureReason';
        if (expr.name === 'NOTHING') return 'null';
        if (expr.name === 'TRUE') return 'true';
        if (expr.name === 'FALSE') return 'false';
        return expr.name;

      case 'FieldAccessExpr':
        return expr.path.join('.');

      case 'BinaryExpr':
        return this.emitBinaryExpr(expr.left, expr.operator, expr.right);

      case 'UnaryExpr':
        if (expr.operator === 'NOT') return `!(${this.emitExpr(expr.operand)})`;
        return `-(${this.emitExpr(expr.operand)})`;

      case 'FunctionCallExpr': {
        const name = expr.name;
        // Built-in functions
        if (name === 'NOW') return 'Date.now()';
        if (name === 'UUID') return 'crypto.randomUUID()';
        if (name === 'LENGTH') {
          const arg = expr.args[0]?.value;
          return arg ? `(${this.emitExpr(arg)}).length` : '0';
        }
        // Regular function call with named args
        if (expr.args.length > 0) {
          const args = `{ ${expr.args.map(a => `${a.name}: ${this.emitExpr(a.value)}`).join(', ')} }`;
          return `await ${name}(${args})`;
        }
        return `await ${name}()`;
      }

      case 'ReadExpr':
        return `__ctx.readField?.('${expr.field.join('.')}')`;

      case 'RecordLiteralExpr':
        return this.emitRecord(expr.fields);

      case 'ListLiteralExpr':
        return `[${expr.elements.map(e => this.emitExpr(e)).join(', ')}]`;

      case 'MakeExpr':
        return `new ${expr.typeName}(${this.emitExpr(expr.source)})`;

      case 'CastExpr':
        return `/** @type {${expr.targetType}} */ (${this.emitExpr(expr.value)})`;

      case 'PriorExpr':
        return `__prior['${expr.field.join('.')}']`;

      case 'SafeAccessExpr':
        return `(${this.emitExpr(expr.base)})?.${expr.field}`;

      case 'OtherwiseExpr':
        return `(${this.emitExpr(expr.value)} ?? ${this.emitExpr(expr.fallback)})`;

      default:
        return `/* unknown expr: ${(expr as any).kind} */ undefined`;
    }
  }

  private emitBinaryExpr(left: Expression, op: string, right: Expression): string {
    const l = this.emitExpr(left);
    const r = this.emitExpr(right);

    switch (op) {
      case 'PLUS': return `(${l} + ${r})`;
      case 'MINUS': return `(${l} - ${r})`;
      case 'TIMES': return `(${l} * ${r})`;
      case 'DIVIDED_BY': return `(${l} / ${r})`;
      case 'MOD': return `(${l} % ${r})`;
      case 'EQUALS': return `(${l} === ${r})`;
      case 'NOT_EQUALS': return `(${l} !== ${r})`;
      case 'GREATER_THAN': return `(${l} > ${r})`;
      case 'LESS_THAN': return `(${l} < ${r})`;
      case 'GREATER_OR_EQUAL': return `(${l} >= ${r})`;
      case 'LESS_OR_EQUAL': return `(${l} <= ${r})`;
      case 'AND': return `(${l} && ${r})`;
      case 'OR': return `(${l} || ${r})`;
      default: return `(${l} /* ${op} */ ${r})`;
    }
  }

  private emitRecord(fields: RecordField[]): string {
    if (fields.length === 0) return '{}';
    const entries = fields.map(f => {
      if (f.name === '__type') {
        return `__type: ${this.emitExpr(f.value)}`;
      }
      return `${f.name}: ${this.emitExpr(f.value)}`;
    });
    return `{ ${entries.join(', ')} }`;
  }

  // ==========================================================================
  // Spec Expressions → JavaScript (for ENSURE blocks in generated code)
  // ==========================================================================

  private emitSpecExpr(expr: import('../ast/nodes.js').SpecExpression, useCurrentFields = false): string {
    switch (expr.kind) {
      case 'SpecComparison': {
        const l = this.emitSpecValue(expr.left, useCurrentFields);
        const r = this.emitSpecValue(expr.right, useCurrentFields);
        switch (expr.operator) {
          case 'EQUALS': return `(${l} === ${r})`;
          case 'NOT_EQUALS': return `(${l} !== ${r})`;
          case 'GREATER_THAN': return `(${l} > ${r})`;
          case 'LESS_THAN': return `(${l} < ${r})`;
          case 'GREATER_OR_EQUAL': return `(${l} >= ${r})`;
          case 'LESS_OR_EQUAL': return `(${l} <= ${r})`;
          default: return 'false';
        }
      }
      case 'SpecBinary':
        return `(${this.emitSpecExpr(expr.left, useCurrentFields)} ${expr.operator === 'AND' ? '&&' : '||'} ${this.emitSpecExpr(expr.right, useCurrentFields)})`;
      case 'SpecNot':
        return `!(${this.emitSpecExpr(expr.operand, useCurrentFields)})`;
      case 'SpecIsNothing': {
        const field = this.emitSpecValue(expr.field, useCurrentFields);
        return expr.negated ? `(${field} != null)` : `(${field} == null)`;
      }
      case 'SpecContains': {
        const coll = this.emitSpecValue(expr.collection, useCurrentFields);
        const val = this.emitSpecValue(expr.value, useCurrentFields);
        return `(Array.isArray(${coll}) ? ${coll}.includes(${val}) : false)`;
      }
      case 'SpecLength':
        return `((${this.emitSpecValue(expr.collection, useCurrentFields)})?.length ?? 0)`;
      case 'SpecIn': {
        const field = this.emitSpecValue(expr.field, useCurrentFields);
        const vals = expr.values.map(v => this.emitExpr(v)).join(', ');
        return expr.negated ? `![${vals}].includes(${field})` : `[${vals}].includes(${field})`;
      }
      case 'SpecReturnValue':
        return '__returnValue';
      case 'SpecPrior':
        return `__prior['${expr.field.join('.')}']`;
      case 'SpecArithmetic': {
        const l = this.emitSpecValue(expr.left, useCurrentFields);
        const r = this.emitSpecValue(expr.right, useCurrentFields);
        const ops: Record<string, string> = { PLUS: '+', MINUS: '-', TIMES: '*', DIVIDED_BY: '/', MOD: '%' };
        return `(${l} ${ops[expr.operator] || '+'} ${r})`;
      }
      case 'SpecFieldRef':
        return this.emitSpecFieldRef(expr.path, useCurrentFields);
      case 'SpecConditional': {
        const cond = this.emitSpecExpr(expr.condition, useCurrentFields);
        const body = expr.body.map(b => this.emitSpecExpr(b, useCurrentFields)).join(' && ');
        return `(!(${cond}) || (${body}))`;
      }
      case 'SpecQuantifier': {
        const coll = this.emitSpecValue(expr.collection, useCurrentFields);
        const method = expr.quantifier === 'ALL' ? 'every' : 'some';
        const body = this.emitSpecExpr(expr.condition, useCurrentFields);
        return `(${coll}).${method}((${expr.variable}) => ${body})`;
      }
      default:
        return 'true';
    }
  }

  private emitSpecValue(expr: import('../ast/nodes.js').SpecExpression, useCurrentFields: boolean): string {
    if (expr.kind === 'SpecFieldRef') return this.emitSpecFieldRef(expr.path, useCurrentFields);
    if (expr.kind === 'SpecReturnValue') return '__returnValue';
    if (expr.kind === 'SpecPrior') return `__prior['${expr.field.join('.')}']`;
    if (expr.kind === 'SpecArithmetic') {
      const l = this.emitSpecValue(expr.left, useCurrentFields);
      const r = this.emitSpecValue(expr.right, useCurrentFields);
      const ops: Record<string, string> = { PLUS: '+', MINUS: '-', TIMES: '*', DIVIDED_BY: '/', MOD: '%' };
      return `(${l} ${ops[expr.operator] || '+'} ${r})`;
    }
    if (expr.kind === 'SpecLength') {
      return `((${this.emitSpecValue(expr.collection, useCurrentFields)})?.length ?? 0)`;
    }
    // Fallback to full spec expression
    return this.emitSpecExpr(expr, useCurrentFields);
  }

  private emitSpecFieldRef(path: string[], useCurrentFields: boolean): string {
    const key = path.join('.');
    // Detect literals encoded as field refs
    if (path.length === 1) {
      if (/^-?\d+(\.\d+)?$/.test(path[0])) return path[0];
      if (path[0] === 'TRUE' || path[0] === 'true') return 'true';
      if (path[0] === 'FALSE' || path[0] === 'false') return 'false';
      if (path[0] === 'NOTHING' || path[0] === 'null') return 'null';
    }
    if (useCurrentFields) {
      return `(__current['${key}'] ?? ${key})`;
    }
    return `(__ctx.readField?.('${key}') ?? ${key})`;
  }

  // ==========================================================================
  // Type Definitions
  // ==========================================================================

  private emitType(def: TypeDef): void {
    this.emit('/**');
    this.emit(` * @typedef {${def.baseType}} ${def.name}`);
    for (const c of def.constraints) {
      this.emit(` * @constraint ${c}`);
    }
    this.emit(' */');

    // Factory function with validation
    this.emit(`export function ${def.name}(value) {`);
    this.indent++;
    for (const constraint of def.constraints) {
      this.emit(`// CONSTRAIN: ${constraint}`);
    }
    if (def.normalize) {
      this.emit(`// NORMALIZE: ${def.normalize}`);
    }
    this.emit('return value;');
    this.indent--;
    this.emit('}');
  }

  private emitData(def: DataDef): void {
    this.emit('/**');
    this.emit(` * @typedef {Object} ${def.name}`);
    for (const f of def.fields) {
      this.emit(` * @property {${this.typeToJSDoc(f.fieldType)}} ${f.name}`);
    }
    this.emit(' */');

    // Constructor function
    this.emit(`export function ${def.name}(data) {`);
    this.indent++;
    this.emit(`return { __type: '${def.name}', ...data };`);
    this.indent--;
    this.emit('}');
  }

  private emitEnum(def: EnumDef): void {
    this.emit(`/** @enum {string} */`);
    this.emit(`export const ${def.name} = Object.freeze({`);
    this.indent++;
    for (const v of def.values) {
      this.emit(`${v}: '${v}',`);
    }
    this.indent--;
    this.emit('});');
  }

  private emitUnion(def: UnionDef): void {
    this.emit('/**');
    this.emit(` * @typedef {${def.variants.map(v => v.name).join(' | ')}} ${def.name}`);
    this.emit(' */');

    for (const variant of def.variants) {
      this.emit(`export function ${variant.name}(data) {`);
      this.indent++;
      this.emit(`return { __type: '${variant.name}', ...data };`);
      this.indent--;
      this.emit('}');
    }
  }

  private emitAlias(def: AliasDef): void {
    this.emit(`/** @typedef {${def.targetType}} ${def.name} */`);
  }

  private emitValidator(def: ValidatorDef): void {
    this.emit(`/** Validator: ${def.name} — applies to ${def.appliesTo} */`);
    this.emit(`export function __validate_${def.name}(value) {`);
    this.indent++;
    this.emit(`// CHECK: ${def.check}`);
    this.emit(`// MESSAGE: ${def.message}`);
    this.emit('return true; // TODO: compile constraint');
    this.indent--;
    this.emit('}');
  }

  private emitExternal(def: ExternalDef): void {
    this.emit(`/** @external ${def.name} — ${def.intent} */`);
    const params = def.parameters.map(p => p.name).join(', ');
    this.emit(`export async function ${def.name}(${params ? `{ ${params} }` : ''}) {`);
    this.indent++;
    this.emit(`throw new Error('External function ${def.name} must be provided by the runtime');`);
    this.indent--;
    this.emit('}');
  }

  // ==========================================================================
  // Runtime Helpers
  // ==========================================================================

  private emitRuntimeHelpers(): void {
    this.emit('');
    this.emit('// ============================================================================');
    this.emit('// VibeL Runtime Helpers (embedded)');
    this.emit('// ============================================================================');
    this.emit('');
    this.emit('class __VibeAbort extends Error {');
    this.indent++;
    this.emit('constructor(reason) { super(reason); this.reason = reason; this.name = "VibeAbort"; }');
    this.indent--;
    this.emit('}');
  }

  // ==========================================================================
  // Type → JSDoc
  // ==========================================================================

  private typeToJSDoc(type: TypeExpr): string {
    switch (type.kind) {
      case 'SimpleType': return type.name;
      case 'OptionalType': return `(${this.typeToJSDoc(type.inner)} | null)`;
      case 'ListType': return `Array<${this.typeToJSDoc(type.elementType)}>`;
      case 'MapType': return `Map<${this.typeToJSDoc(type.keyType)}, ${this.typeToJSDoc(type.valueType)}>`;
      case 'EitherType': return `(${this.typeToJSDoc(type.left)} | ${this.typeToJSDoc(type.right)})`;
      default: return 'any';
    }
  }

  // ==========================================================================
  // Output Helpers
  // ==========================================================================

  private emit(line: string): void {
    if (line === '') {
      this.output.push('');
      return;
    }
    const prefix = '  '.repeat(this.indent);
    this.output.push(prefix + line);
  }
}
